name: parking_lot
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  path_provider: ^2.0.8
  isar: ^2.0.0
  isar_flutter_libs: ^2.0.0
  isar_connect: ^2.0.0
  get: ^4.6.1
  flutter_screenutil: ^5.1.1
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  animated_theme_switcher: ^2.0.6
  intl: ^0.17.0
  month_picker_dialog: ^0.4.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  isar_generator: ^2.0.0
  build_runner: ^2.1.7

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
   #- family: appIcons
      #fonts:
    #    - asset: assets/fonts/app_icons/appIcons.ttf

    - family: ZonaPro
      fonts:
        - asset: assets/fonts/zona_pro/ZonaPro-Hairline.ttf
          weight: 100
        - asset: assets/fonts/zona_pro/ZonaPro-Thin.ttf
          weight: 200
        - asset: assets/fonts/zona_pro/ZonaPro-Light.ttf
          weight: 300
        - asset: assets/fonts/zona_pro/ZonaPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/zona_pro/ZonaPro-Regular.ttf
          weight: 500
        - asset: assets/fonts/zona_pro/ZonaPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/zona_pro/ZonaPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/zona_pro/ZonaPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/zona_pro/ZonaPro-Black.ttf
          weight: 900