name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Flutter action
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - name: Analyze
      run: flutter analyze
    - name: Run tests
      run: flutter test